from typing import Protocol


class CommandDispatcherPort(Protocol):
    def start(self) -> None: ...

    def enqueue(self, gesture: str, command: str) -> None: ...

    @property
    def queue_depth(self) -> int: ...

    @property
    def dropped_commands(self) -> int: ...

    @property
    def last_send_latency_seconds(self) -> float | None: ...

    async def close(self) -> None: ...
