from typing import Any, Protocol


class FrameSourcePort(Protocol):
    def is_open(self) -> bool: ...

    def start(self) -> None: ...

    def latest_versioned(self) -> tuple[int, Any | None]: ...

    def failed(self) -> bool: ...

    def stop(self) -> None: ...

    def close(self) -> None: ...
