from typing import Protocol


class VoiceStreamPort(Protocol):
    def send_chunk(self, chunk: bytes) -> None: ...

    def end(self) -> None: ...


class TVRemotePort(Protocol):
    async def connect(self) -> bool: ...

    async def send_key_command(self, command: str) -> None: ...

    async def start_voice(self) -> VoiceStreamPort | None: ...

    async def disconnect(self) -> None: ...
